language: go

go:
  - 1.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x

sudo: required

before_install:
  - ./tools/install_engine_travis.sh
  - source ./tools/install_engine_travis_source.sh
  - ./tools/install_engine_travis_run.sh

script:
  - go build
  